const cart = JSON.parse(localStorage.getItem('qa-cart') || '[]');

function saveCart(){ localStorage.setItem('qa-cart', JSON.stringify(cart)); updateCartCount(); }
function updateCartCount(){ const el=document.getElementById('cart-count'); if(el) el.textContent=cart.length; }
function addToCart(name,price){ cart.push({name,price}); saveCart(); showCart(); }
function showCart(){ const drawer=document.getElementById('cart-drawer'); if(!drawer) return; drawer.classList.add('open'); drawer.setAttribute('aria-hidden','false'); renderCart(); }
function hideCart(){ const drawer=document.getElementById('cart-drawer'); if(drawer){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');} }
function renderCart(){ const list=document.getElementById('cart-items'); const total=document.getElementById('cart-total'); if(!list||!total)return; list.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-line"><span>${x.name}</span><span>$${x.price.toFixed(2)} <button onclick="removeCart(${i})" aria-label="Remove">×</button></span></div>`).join(''):'<p>Your cart is empty.</p>'; total.textContent='$'+cart.reduce((s,x)=>s+x.price,0).toFixed(2); }
function removeCart(i){ cart.splice(i,1); saveCart(); renderCart(); }
function mockCheckout(){ alert('Checkout placeholder. Next step: connect Stripe Checkout or Stripe Payment Element for cards, Apple Pay, and Google Pay.'); }
function homeSearch(value){ const q=value.toLowerCase(); document.querySelectorAll('#featured-grid .product-card').forEach(card=>card.style.display=card.dataset.search.includes(q)?'block':'none'); }
function submitContact(e){ e.preventDefault(); document.getElementById('form-status').textContent='Prototype submitted. Connect this form to your email or backend when the site is deployed.'; e.target.reset(); }

function setupMarketplace(){
  const cards=[...document.querySelectorAll('.store-card')]; if(!cards.length)return;
  let currentFilter='all'; const search=document.getElementById('document-search'); const sort=document.getElementById('sort-select'); const grid=document.getElementById('document-grid');
  function apply(){ const q=(search?.value||'').toLowerCase(); cards.forEach(c=>{const okFilter=currentFilter==='all'||c.dataset.category===currentFilter;const okSearch=c.dataset.search.includes(q)||c.dataset.title.toLowerCase().includes(q);c.style.display=okFilter&&okSearch?'block':'none';}); }
  document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');currentFilter=btn.dataset.filter;apply();}));
  search?.addEventListener('input',apply);
  sort?.addEventListener('change',()=>{const sorted=[...cards].sort((a,b)=>{if(sort.value==='price-low')return +a.dataset.price-+b.dataset.price;if(sort.value==='price-high')return +b.dataset.price-+a.dataset.price;if(sort.value==='title')return a.dataset.title.localeCompare(b.dataset.title);return 0;});sorted.forEach(c=>grid.appendChild(c));});
}

const productData={
  'event-driven':{title:'Event Driven Trading System',cat:'Trading Systems',price:49,desc:'A practical architecture document for building an event-driven electronic trading system.',cover:'cover-dark',kicker:'EVENT DRIVEN',coverTitle:'TRADING SYSTEM',sub:'Architecture & Design',items:['System overview and architectural goals','Gateway, book builder, strategy, order manager, and risk responsibilities','Event flow and SPSC queue boundaries','Execution, P&L, and kill-switch considerations']},
  'options-pricing':{title:'Options Pricing Models',cat:'Options & Derivatives',price:49,desc:'A reusable quantitative framework for implementing common option-pricing techniques.',cover:'cover-cyan',kicker:'OPTIONS PRICING',coverTitle:'MODELS',sub:'Derivatives Engineering',items:['Black–Scholes model structure','Monte Carlo simulation workflow','Finite-difference architecture','Greeks and numerical validation']},
  'low-latency':{title:'Low Latency Design',cat:'Infrastructure',price:49,desc:'Patterns for building high-throughput, low-latency financial applications.',cover:'cover-light',kicker:'LOW LATENCY',coverTitle:'DESIGN',sub:'Performance Engineering',items:['Concurrency and queue design','Memory reuse and allocation discipline','Logging and observability trade-offs','Benchmarking and performance testing']},
  'market-data':{title:'Market Data Pipeline',cat:'Market Data',price:39,desc:'A reference pipeline for receiving, normalizing, and routing market data.',cover:'cover-blue',kicker:'MARKET DATA',coverTitle:'PIPELINE',sub:'Feeds & Processing',items:['WebSocket/feed ingestion','Trade, quote, and bar normalization','Event routing architecture','Persistence and downstream consumers']},
  'risk':{title:'Risk Management Framework',cat:'Risk Management',price:39,desc:'A technical design for pre-trade and runtime controls in a trading application.',cover:'cover-blue',kicker:'RISK MANAGEMENT',coverTitle:'FRAMEWORK',sub:'Controls & Limits',items:['Position and notional limits','Realized and unrealized P&L','Order validation checks','Emergency kill-switch flow']},
  'exchange':{title:'Exchange Architecture',cat:'Infrastructure',price:59,desc:'A system-design document for a simplified electronic exchange and matching engine.',cover:'cover-slate',kicker:'EXCHANGE',coverTitle:'ARCHITECTURE',sub:'Matching & Order Books',items:['Order gateway design','Limit-order book model','Matching-engine workflow','Market-event publication']},
  'strategy':{title:'Strategy Development',cat:'Research',price:39,desc:'A disciplined framework for moving from a research idea to a testable trading strategy.',cover:'cover-cyan',kicker:'STRATEGY',coverTitle:'DEVELOPMENT',sub:'Research Workflow',items:['Hypothesis and signal design','Feature construction','Backtest workflow','Deployment-readiness checklist']},
  'cpp':{title:'C++ Financial Engineering',cat:'Mathematics',price:49,desc:'Implementation patterns for computational finance and numerical methods in C++.',cover:'cover-slate',kicker:'C++',coverTitle:'FINANCIAL ENGINEERING',sub:'Numerical Methods',items:['Normal CDF and inverse approximations','Monte Carlo pricing','Finite-difference methods','Numerical validation and testing']}
};
function setupProduct(){const t=document.getElementById('detail-title');if(!t)return;const key=new URLSearchParams(location.search).get('doc')||'event-driven';const d=productData[key]||productData['event-driven'];document.title=d.title+' | Quantitative Applications';t.textContent=d.title;document.getElementById('detail-category').textContent=d.cat;document.getElementById('detail-price').textContent='$'+d.price.toFixed(2);document.getElementById('detail-description').textContent=d.desc;const c=document.getElementById('detail-cover');c.className='cover large-cover '+d.cover;c.innerHTML=`<span>${d.kicker}</span><strong>${d.coverTitle}</strong><small>${d.sub}</small>`;document.getElementById('detail-list').innerHTML=d.items.map(x=>`<li>${x}</li>`).join('');document.getElementById('buy-button').onclick=()=>{cart.push({name:d.title,price:d.price});saveCart();alert(d.title+' added to cart. Open the Documents page to view the cart prototype.');};}

document.addEventListener('DOMContentLoaded',()=>{updateCartCount();setupMarketplace();setupProduct();});
